"""Tools for rewriting a book into concise Chinese text using LLM.

Workflow:
- Parse an outline TXT (generated by outline-gen) into a tree.
- Treat leaf nodes as the smallest semantic units.
- For each leaf node, extract the corresponding page range from the PDF.
- Ask the LLM to produce a concise Chinese rewrite for that leaf,
  organized according to a recommended logical skeleton for the book type.
- Save each rewritten leaf as a Markdown file under a MkDocs project
  directory, using the mkdocs-material theme.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Dict, Tuple

from openai import OpenAI
from rich.console import Console
from rich.panel import Panel

from .config import Config
from .pdf_processor import PDFProcessor


@dataclass
class OutlineEntry:
    """Represents a single outline node parsed from outline TXT."""

    title: str
    page: int  # 1-indexed global page number
    level: int  # 0 = top-level, increasing with depth
    children: List["OutlineEntry"] = field(default_factory=list)
    parent: Optional["OutlineEntry"] = None


BOOK_TYPE_CONFIG: Dict[str, Dict[str, str]] = {
    "novel": {
        "label": "小说",
        "expectation": "张力与沉浸",
        "skeleton": "目标-阻碍-选择-结果-钩子",
    },
    "narrative_nonfiction": {
        "label": "纪实叙事",
        "expectation": "真实与解释",
        "skeleton": "场景-问题-证据-解释-意义",
    },
    "history": {
        "label": "历史",
        "expectation": "因果与脉络",
        "skeleton": "背景-事件-机制-影响-争议",
    },
    "philosophy": {
        "label": "哲学/思辨",
        "expectation": "概念澄清",
        "skeleton": "问题-论证-反驳-回应",
    },
    "argument": {
        "label": "议论文/观点",
        "expectation": "说服与判断",
        "skeleton": "主张-证据-反方-权衡",
    },
    "biography": {
        "label": "传记/回忆录",
        "expectation": "人与命运",
        "skeleton": "阶段-转折-关系-代价",
    },
    "self_help": {
        "label": "自助/成长",
        "expectation": "可持续改变",
        "skeleton": "困境-观念-练习-复盘-失败",
    },
    "business_case": {
        "label": "商业案例",
        "expectation": "可迁移经验",
        "skeleton": "情境-决策-取舍-复盘",
    },
    "poetry": {
        "label": "诗歌/散文",
        "expectation": "余韵与多义",
        "skeleton": "意象-转折-语言-留白",
    },
}

BOOK_TYPE_ALIASES: Dict[str, str] = {
    "novel": "novel",
    "小说": "novel",
    "story": "novel",
    "fiction": "novel",
    "narrative_nonfiction": "narrative_nonfiction",
    "纪实叙事": "narrative_nonfiction",
    "nonfiction": "narrative_nonfiction",
    "history": "history",
    "历史": "history",
    "philosophy": "philosophy",
    "哲学": "philosophy",
    "思辨": "philosophy",
    "argument": "argument",
    "议论文": "argument",
    "观点": "argument",
    "biography": "biography",
    "传记": "biography",
    "回忆录": "biography",
    "memoir": "biography",
    "self_help": "self_help",
    "自助": "self_help",
    "成长": "self_help",
    "business_case": "business_case",
    "商业案例": "business_case",
    "case": "business_case",
    "poetry": "poetry",
    "散文": "poetry",
    "诗歌": "poetry",
}


console = Console()


class BookRewriter:
    """Rewrite a book into concise Chinese text using LLM and MkDocs structure."""

    def __init__(
        self,
        pdf_path: str,
        outline_txt_path: str,
        output_root: str,
        book_type: str,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
    ):
        self.pdf_path = Path(pdf_path)
        self.outline_txt_path = Path(outline_txt_path)
        self.output_root = Path(output_root)

        if not self.pdf_path.exists():
            raise FileNotFoundError(f"PDF not found: {self.pdf_path}")
        if not self.outline_txt_path.exists():
            raise FileNotFoundError(f"Outline TXT not found: {self.outline_txt_path}")

        self.book_type_key = self._normalize_book_type(book_type)
        self.book_type_config = BOOK_TYPE_CONFIG[self.book_type_key]

        cfg = Config()
        api_key = api_key or cfg.get_api_key()
        if not api_key:
            raise ValueError("DASHSCOPE_API_KEY not found in environment or config")

        self.model = model or cfg.get_model()
        self.client = OpenAI(
            api_key=api_key,
            base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        )

    def _normalize_book_type(self, book_type: str) -> str:
        key = book_type.strip().lower()
        if key in BOOK_TYPE_ALIASES:
            return BOOK_TYPE_ALIASES[key]
        # Try raw key if it matches directly
        if key in BOOK_TYPE_CONFIG:
            return key
        raise ValueError(f"Unsupported book type: {book_type}")

    def _parse_outline(self) -> List[OutlineEntry]:
        """Parse outline TXT into a tree of OutlineEntry objects."""
        with open(self.outline_txt_path, "r", encoding="utf-8") as f:
            raw_lines = f.readlines()

        roots: List[OutlineEntry] = []
        stack: List[OutlineEntry] = []

        for raw in raw_lines:
            line = raw.rstrip("\n")
            if not line.strip():
                continue

            # Level is determined by leading tabs, consistent with OutlineNode.flatten
            indent = len(line) - len(line.lstrip("\t"))
            stripped = line.lstrip("\t")

            # Lines without trailing page number are treated as title continuations;
            # only lines ending with an integer page are used as actual nodes.
            m = re.match(r"(.+?)\s+(\d+)$", stripped)
            if not m:
                continue

            title = m.group(1).strip()
            page = int(m.group(2))
            entry = OutlineEntry(title=title, page=page, level=indent)

            while stack and stack[-1].level >= indent:
                stack.pop()

            if stack:
                entry.parent = stack[-1]
                stack[-1].children.append(entry)
            else:
                roots.append(entry)

            stack.append(entry)

        return roots

    def _collect_leaf_entries(self, roots: List[OutlineEntry]) -> List[OutlineEntry]:
        """Collect all leaf entries (nodes without children) in reading order."""
        leaves: List[OutlineEntry] = []

        def dfs(node: OutlineEntry):
            if not node.children:
                leaves.append(node)
            else:
                for child in node.children:
                    dfs(child)

        for root in roots:
            dfs(root)

        # Sort by page and level to preserve reading order
        leaves.sort(key=lambda e: (e.page, e.level))
        return leaves

    def _build_leaf_page_ranges(
        self,
        leaves: List[OutlineEntry],
        total_pages: int,
    ) -> List[Tuple[OutlineEntry, int, int]]:
        """
        Given leaf entries and total page count, derive [start, end] ranges
        (1-indexed, inclusive) for each leaf based on its starting page and
        the next leaf's starting page.
        """
        if not leaves:
            return []

        ranges: List[Tuple[OutlineEntry, int, int]] = []
        for idx, leaf in enumerate(leaves):
            start_page = max(leaf.page, 1)
            if idx < len(leaves) - 1:
                next_start = max(leaves[idx + 1].page, start_page)
                end_page = max(start_page, next_start - 1)
            else:
                end_page = total_pages

            ranges.append((leaf, start_page, end_page))

        return ranges

    def _truncate_text(self, text: str, max_chars: int = 15000) -> str:
        """Soft truncate very long text to avoid overly large prompts."""
        if len(text) <= max_chars:
            return text
        return text[:max_chars]

    def _postprocess_markdown(self, text: str) -> str:
        """
        Post-process LLM output to enforce:
        - No headings (lines starting with '#')
        - No bullet/numbered lists
        - No obvious separators like '---'
        Result is still valid Markdown but essentially plain paragraphs.
        """
        lines: List[str] = []

        for raw in text.splitlines():
            line = raw.rstrip()
            if not line.strip():
                # Preserve single blank lines; we'll collapse later.
                lines.append("")
                continue

            stripped = line.lstrip()

            # Skip headings
            if stripped.startswith("#"):
                continue

            # Skip bullet lists
            if stripped.startswith(("-", "*", "+")) and len(stripped) > 1 and stripped[1].isspace():
                continue

            # Skip numbered lists like "1. xxx"
            if re.match(r"^\d+\.\s+", stripped):
                continue

            # Skip obvious separators
            if re.match(r"^[-_*]{3,}$", stripped):
                continue

            lines.append(line)

        # Collapse multiple blank lines
        cleaned: List[str] = []
        blank_count = 0
        for line in lines:
            if not line.strip():
                blank_count += 1
                if blank_count <= 1:
                    cleaned.append("")
            else:
                blank_count = 0
                cleaned.append(line)

        return "\n".join(cleaned).strip()

    def _rewrite_leaf(self, leaf: OutlineEntry, raw_text: str) -> str:
        """Use LLM to rewrite a single leaf section into concise Chinese text."""
        if not raw_text.strip():
            return ""

        raw_text = self._truncate_text(raw_text)

        cfg = self.book_type_config
        label = cfg["label"]
        expectation = cfg["expectation"]
        skeleton = cfg["skeleton"]

        prompt = (
            "你将看到一本书中某个小节的原文片段（可能跨越若干页）。\n"
            "请基于这段原文，用流畅自然的简体中文重写一个“精简版正文”。\n\n"
            f"书籍类型：{label}\n"
            f"读者主要期待：{expectation}\n"
            f"推荐的隐含组织骨架关键词：{skeleton}\n\n"
            "请在内部构思时，可以参考上述骨架关键词的顺序来组织材料，"
            "但不要在文本中显式写出这些词语或任何结构标签。\n\n"
            "输出严格遵守以下要求：\n"
            "1. 只输出正文内容，不要输出任何标题、小标题或分隔符。\n"
            "2. 不要使用任何 Markdown 标记或列表：禁止以 #、*、-、+、数字加点 等形式开头的行，"
            "也不要使用 --- 之类的分割线。\n"
            "3. 用 3–7 个自然段讲清这一部分的核心内容，删去枝节、例行前言或结语，只保留对理解最关键的东西。\n"
            "4. 无论原文是否为英文，你的输出必须全部使用简体中文，可以保留极少量必要的英文缩写（如 GDP、FDI、PMI 等）。\n"
            "5. 不要显式描述结构（例如“首先…其次…最后…”），而是像一本已经编辑好的中文书的正文那样自然展开。\n\n"
            f"当前小节标题（供你把握上下文，不要照抄为标题使用）：{leaf.title}\n"
            f"大致所在页码：第{leaf.page}页附近。\n\n"
            "以下是原文片段，请开始分析并重写：\n"
            "---------------- 原文开始 ----------------\n"
            f"{raw_text}\n"
            "---------------- 原文结束 ----------------\n"
        )

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "你是一名专业的中文图书编辑，擅长在保持作者观点和信息完整性的前提下，"
                        "将冗长的章节改写成条理清晰、易读的精简版正文。你输出的所有内容必须是简体中文。"
                    ),
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
            temperature=0.5,
        )

        content = response.choices[0].message.content or ""
        return self._postprocess_markdown(content)

    def _short_title(self, title: str) -> str:
        """Create a short, readable title for navigation."""
        t = title.strip()
        if len(t) > 40:
            t = t[:37] + "..."
        return t

    def _slugify(self, text: str) -> str:
        """
        Create a filesystem-friendly slug from a title.

        - Preserve Chinese characters and most punctuation;
        - Remove or replace characters that are problematic in file paths;
        - Collapse consecutive whitespace into single underscores.
        """
        t = text.strip()
        if not t:
            return "untitled"

        # Replace path-unfriendly characters
        t = re.sub(r"[\\/:*?\"<>|]", "_", t)
        # Collapse whitespace into single underscore
        t = re.sub(r"\s+", "_", t)
        # Avoid very long names
        if len(t) > 80:
            t = t[:77] + "..."
        return t

    def _build_nav_lines(
        self,
        roots: List[OutlineEntry],
        leaf_to_filename: Dict[int, str],
        indent: int = 2,
    ) -> List[str]:
        """
        Build hierarchical MkDocs nav lines from the original outline tree.

        - Internal nodes（有 children）作为分组，不直接指向文件；
        - 叶子节点指向对应的 Markdown 文件；
        - 缩进和层级与原始 outline.txt 中的标签结构保持一致。
        """
        lines: List[str] = []

        def dfs(node: OutlineEntry, level_indent: int) -> List[str]:
            prefix = " " * level_indent
            safe_title = self._short_title(node.title).replace(":", "：").replace("\"", "”")
            filename = leaf_to_filename.get(id(node))

            # Leaf node -> actual page with file
            if not node.children:
                if not filename:
                    return []
                return [f"{prefix}- \"{safe_title}\": {filename}"]

            # Non-leaf node -> group; children nested under it
            child_lines: List[str] = []
            for child in node.children:
                child_lines.extend(dfs(child, level_indent + 2))

            if not child_lines:
                return []

            return [f"{prefix}- \"{safe_title}\":"] + child_lines

        for root in roots:
            lines.extend(dfs(root, indent))

        return lines

    def rewrite_book(self) -> None:
        """
        High-level orchestration:
        - Parse outline TXT.
        - Collect leaf nodes and derive page ranges.
        - Extract text for each leaf and rewrite with LLM.
        - For each leaf:
          - Save the rewritten content immediately to a Markdown file.
          - Print the generated content to stdout.
          - Print a simple progress bar based on covered pages.
        - Finally generate MkDocs project config with mkdocs-material theme.
        """
        roots = self._parse_outline()
        if not roots:
            raise ValueError(f"No outline entries parsed from {self.outline_txt_path}")

        leaves = self._collect_leaf_entries(roots)
        if not leaves:
            raise ValueError("Outline TXT does not contain any leaf entries.")

        # Prepare MkDocs output structure
        self.output_root.mkdir(parents=True, exist_ok=True)
        docs_dir = self.output_root / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)

        book_name = self.pdf_path.stem
        index_text_lines = [
            f"{book_name} 精简版",
            "",
            "本网站由 outline-gen 工具自动提取原书结构，"
            "并通过大模型按章节生成精简版中文正文，仅供学习与研究使用。",
        ]
        (docs_dir / "index.md").write_text("\n".join(index_text_lines) + "\n", encoding="utf-8")

        # Map each leaf OutlineEntry (by id) to its generated filename
        leaf_to_filename: Dict[int, str] = {}

        with PDFProcessor(str(self.pdf_path)) as processor:
            total_pages = processor.get_page_count()
            ranges = self._build_leaf_page_ranges(leaves, total_pages)

            total_leaves = len(ranges)

            for idx, (leaf, start_page, end_page) in enumerate(ranges, start=1):
                raw_text = processor.extract_text_for_page_range(start_page, end_page)
                md_text = self._rewrite_leaf(leaf, raw_text)

                # Build hierarchical folder path based on outline structure.
                # All ancestors (excluding the leaf itself) become nested folders,
                # the leaf itself becomes an .md file inside the deepest folder.
                ancestors: List[OutlineEntry] = []
                parent = leaf.parent
                while parent is not None:
                    ancestors.append(parent)
                    parent = parent.parent
                ancestors.reverse()

                folder = docs_dir
                for anc in ancestors:
                    segment = self._slugify(self._short_title(anc.title))
                    folder = folder / segment
                folder.mkdir(parents=True, exist_ok=True)

                # Use a slugified short title as file name; ensure uniqueness
                base_name = self._slugify(self._short_title(leaf.title)) or f"section-{idx:03d}"
                file_path = folder / f"{base_name}.md"
                if file_path.exists():
                    suffix = 2
                    while (folder / f"{base_name}-{suffix}.md").exists():
                        suffix += 1
                    file_path = folder / f"{base_name}-{suffix}.md"

                # Save immediately to a Markdown file
                file_path.write_text(md_text.strip() + "\n" if md_text.strip() else "\n", encoding="utf-8")

                # Map leaf to its relative file path (for nav building)
                rel_path = file_path.relative_to(docs_dir).as_posix()
                leaf_to_filename[id(leaf)] = rel_path

                # Progress bar based on pages covered so far
                progress = min(end_page, total_pages) / max(total_pages, 1)
                bar_width = 30
                filled = int(bar_width * progress)
                bar = "█" * filled + "·" * (bar_width - filled)
                percent = progress * 100
                progress_line = (
                    f"[bold green][{bar}][/bold green] "
                    f"[cyan]{percent:.1f}%[/cyan] "
                    f"（已覆盖到第{min(end_page, total_pages)}/{total_pages}页，共{total_pages}页）"
                )

                # Rich output: metadata panel
                meta_text = (
                    f"小节序号：{idx}/{total_leaves}\n"
                    f"小节标题：{leaf.title}\n"
                    f"页码范围：第{start_page}–{end_page}页\n\n"
                    f"{progress_line}"
                )
                console.print(
                    Panel.fit(
                        meta_text,
                        title="[bold cyan]正在生成叶子节点[/bold cyan]",
                        border_style="cyan",
                    )
                )

                # Rich output: generated content panel
                content_preview = md_text.strip() or "[空内容]"
                console.print(
                    Panel(
                        content_preview,
                        title="[bold green]生成内容预览[/bold green]",
                        border_style="green",
                    )
                )

        # Generate mkdocs.yml configured with mkdocs-material theme
        # Enable a few commonly useful Material features by default.
        site_name = f"{book_name} 精简版"
        mkdocs_lines = [
            f"site_name: \"{site_name}\"",
            "theme:",
            "  name: material",
            "  language: zh",
            "  features:",
            "    - navigation.footer",   # 上一页/下一页 按钮
            "    - navigation.top",      # 回到页面顶部按钮
            "    - search.highlight",    # 搜索结果高亮
            "    - search.suggest",      # 搜索联想
            "    - toc.follow",          # 目录跟随滚动高亮
            "    - content.code.copy",   # 代码块一键复制按钮（以后如有代码可用）",
            "nav:",
            "  - 简介: index.md",
        ]

        # Append hierarchical nav built from the original outline structure
        nav_leaf_lines = self._build_nav_lines(roots, leaf_to_filename, indent=2)
        mkdocs_lines.extend(nav_leaf_lines)

        mkdocs_path = self.output_root / "mkdocs.yml"
        mkdocs_path.write_text("\n".join(mkdocs_lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    # Simple CLI for manual use:
    #
    # python -m outline_gen.book_rewriter \
    #   --pdf uc.pdf \
    #   --outline uc.outline.txt \
    #   --output rewritten_book \
    #   --book-type 历史
    import argparse

    parser = argparse.ArgumentParser(description="Rewrite a book into concise Chinese Markdown using LLM.")
    parser.add_argument("--pdf", dest="pdf_path", required=True, help="Path to source PDF file.")
    parser.add_argument("--outline", dest="outline_txt_path", required=True, help="Path to outline TXT file.")
    parser.add_argument("--output", dest="output_root", required=True, help="Output directory for MkDocs project.")
    parser.add_argument(
        "--book-type",
        dest="book_type",
        required=True,
        help="Book type, e.g. 小说 / 历史 / 纪实叙事 / 自助 / 商业案例 等。",
    )
    parser.add_argument("--model", dest="model", default=None, help="LLM model name (default from config).")

    args = parser.parse_args()

    rewriter = BookRewriter(
        pdf_path=args.pdf_path,
        outline_txt_path=args.outline_txt_path,
        output_root=args.output_root,
        book_type=args.book_type,
        model=args.model,
    )
    rewriter.rewrite_book()
